package io.spotnext.kakao.structs;

public enum NSBindingName {
	Alignment("alignment"),
	AlternateImage("alternateImage"),
	AlternateTitle("alternateTitle"),
	Animate("animate"),
	AnimationDelay("animationDelay"),
	Argument("argument"),
	AttributedString("attributedString"),
	ContentArray("contentArray"),
	ContentArrayForMultipleSelection("contentArrayForMultipleSelection"),
	Content("content"),
	ContentDictionary("contentDictionary"),
	ContentHeight("contentHeight"),
	ContentObject("contentObject"),
	ContentObjects("contentObjects"),
	ContentSet("contentSet"),
	ContentValues("contentValues"),
	ContentWidth("contentWidth"),
	CriticalValue("criticalValue"),
	Data("data"),
	DisplayPatternTitle("displayPatternTitle"),
	DisplayPatternValue("displayPatternValue"),
	DocumentEdited("documentEdited"),
	DoubleClickArgument("doubleClickArgument"),
	DoubleClickTarget("doubleClickTarget"),
	Editable("editable"),
	Enabled("enabled"),
	ExcludedKeys("excludedKeys"),
	FilterPredicate("filterPredicate"),
	Font("font"),
	FontBold("fontBold"),
	FontFamilyName("fontFamilyName"),
	FontItalic("fontItalic"),
	FontName("fontName"),
	FontSize("fontSize"),
	HeaderTitle("headerTitle"),
	Hidden("hidden"),
	Image("image"),
	IncludedKeys("includedKeys"),
	InitialKey("initialKey"),
	InitialValue("initialValue"),
	IsIndeterminate("isIndeterminate"),
	Label("label"),
	LocalizedKeyDictionary("localizedKeyDictionary"),
	ManagedObjectContext("managedObjectContext"),
	MaximumRecents("maximumRecents"),
	MaxValue("maxValue"),
	MaxWidth("maxWidth"),
	MinValue("minValue"),
	MinWidth("minWidth"),
	MixedStateImage("mixedStateImage"),
	OffStateImage("offStateImage"),
	OnStateImage("onStateImage"),
	PositioningRect("positioningRect"),
	Predicate("predicate"),
	RecentSearches("recentSearches"),
	RepresentedFilename("representedFilename"),
	RowHeight("rowHeight"),
	SelectedIdentifier("selectedIdentifier"),
	SelectedIndex("selectedIndex"),
	SelectedLabel("selectedLabel"),
	SelectedObject("selectedObject"),
	SelectedObjects("selectedObjects"),
	SelectedTag("selectedTag"),
	SelectedValue("selectedValue"),
	SelectedValues("selectedValues"),
	SelectionIndexes("selectionIndexes"),
	SelectionIndexPaths("selectionIndexPaths"),
	SortDescriptors("sortDescriptors"),
	Target("target"),
	TextColor("textColor"),
	Title("title"),
	ToolTip("toolTip"),
	Transparent("transparent"),
	Value("value"),
	ValuePath("valuePath"),
	ValueURL("valueURL"),
	Visible("visible"),
	WarningValue("warningValue"),
	Width("width");
	
	
	public final String id;

	private NSBindingName(String id) {
		this.id = id;
	}
}
